# Generated by Django 3.2.9 on 2021-12-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bathroom_count',
            field=models.CharField(default='', max_length=100, verbose_name='Bathroom Count'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_link',
            field=models.CharField(default='Image link', max_length=500, verbose_name='Image Link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='max_space',
            field=models.CharField(default='', max_length=100, verbose_name='Max Space'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_space',
            field=models.CharField(default='', max_length=100, verbose_name='Room Space'),
        ),
        migrations.AddField(
            model_name='room',
            name='shower_count',
            field=models.CharField(default='', max_length=100, verbose_name='Shower Count'),
        ),
        migrations.AddField(
            model_name='room',
            name='std_space',
            field=models.CharField(default='', max_length=100, verbose_name='Standard Space'),
        ),
    ]
